[package]
name = "th-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = "0.21.6"
tokio = { version = "1.21.1", features = ["full"] }
# redis-async-pool = "0.2.4"
r2d2_redis = "0.14"